spring:
  application:
    name: graduation-project

  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: event-notificator-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.value.default.type: com.example.graduation_project.kafka.EventChangeMessage
        spring.json.trusted.packages: "*"
      auto-offset-reset: earliest
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.trusted.packages: "*"
    template:
      default-topic: event-changes

jwt:
  lifetime: 86400000
  secret-key: 0wF9OThXPdqtqdmoLHhC1BTSG9YpRNCD

event:
  status:
    cron: "0 * * * * *"