spring:
  application:
    name: graduation-project

  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  lifetime: 86400000
  secret-key: 0wF9OThXPdqtqdmoLHhC1BTSG9YpRNCD

event:
  status:
    cron: "0 * * * * *"